### ISSUE TITLE
ERR_MODULE_NOT_FOUND when running example

### ISSUE THREAD

**Issue by TCH68k** [LuanRT/BgUtils#11]
### Steps to reproduce

```
git clone https://github.com/LuanRT/BgUtils
cd BgUtils/examples/node
npm install
npx tsx .
```

### Failure Logs

```shell
node:internal/modules/run_main:104
    triggerUncaughtException(
    ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/tmp/BgUtils/dist/index.js' imported from /tmp/BgUtils/examples/node/index.ts
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at resolveBase (file:///root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/esm/index.mjs?1735255288906:2:3212)
    at async resolveDirectory (file:///root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/esm/index.mjs?1735255288906:2:3578)
    at async resolve (file:///root/.npm/_npx/fd45a72a545557e9/node_modules/tsx/dist/esm/index.mjs?1735255288906:2:4441)
    at async nextResolve (node:internal/modules/esm/hooks:748:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:240:24)
    at async handleMessage (node:internal/modules/esm/worker:199:18) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///tmp/BgUtils/dist/index.js'
}

Node.js v23.5.0
```

### Expected behavior

I expected that something else than an error would happen.

### Current behavior

An error message of `ERR_MODULE_NOT_FOUND`.

### Version

Default

### Anything else?

I've followed the instructions here: [https://github.com/LuanRT/BgUtils/tree/main/examples/node](https://github.com/LuanRT/BgUtils/tree/main/examples/node)

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
`npm run build` first, then try the example.

Or install the package from NPM and update the imports in the example to use that instead.

**Comment by TCH68k** [comment]
It died with `ERR_MODULE_NOT_FOUND`:
```
> bgutils-js@3.1.0 build
> npm run clean && npm run lint && npm run build:esm && npm run bundle:node


> bgutils-js@3.1.0 clean
> npx rimraf ./dist ./bundle


> bgutils-js@3.1.0 lint
> npx eslint ./src/**/*.ts


Oops! Something went wrong! :(

ESLint: 9.17.0

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@eslint/js' imported from /tmp/BgUtils/eslint.config.js
    at Object.getPackageJSONURL (node:internal/modules/package_json_reader:267:9)
    at packageResolve (node:internal/modules/esm/resolve:768:81)
    at moduleResolve (node:internal/modules/esm/resolve:854:18)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:688:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:612:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:595:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:248:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:136:49)
```
In the main directory, in `src` and in `examples`. In `examples/node` it died because it did not find `build`:
```
npm error Missing script: "build"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-27T18_54_29_157Z-debug-0.log
```
From which directory i should run it?

**Comment by LuanRT** [comment]
Root. You forgot to install the deps (`npm install`).

**Comment by TCH68k** [comment]
The example said:
```
cd examples/node
npm install
npx tsx .
```
You said: _"`npm run build first`, then try the example."_ I did as told. That did not work. You say, it is because i have to run the example's `npm install` before that? I do not understand. I have to run `npm run build` before `cd examples/node && npm install && npx tsx .` and i have to run `npm install` before `npm run build`? Now i am totally confused. When and where should i run `npm install`?

I tried this setup (in root directory as you told me):
```
git clone https://github.com/LuanRT/BgUtils
cd BgUtils
npm install
```
Result:
```
npm error code 2
npm error path /tmp/BgUtils
npm error command failed
npm error command sh -c npm run build
npm error > bgutils-js@3.1.0 build
npm error > npm run clean && npm run lint && npm run build:esm && npm run bundle:node
npm error
npm error
npm error > bgutils-js@3.1.0 clean
npm error > npx rimraf ./dist ./bundle
npm error
npm error
npm error > bgutils-js@3.1.0 lint
npm error > npx eslint ./src/**/*.ts
npm error Oops! Something went wrong! :(
npm error
npm error ESLint: 9.17.0
npm error
npm error Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@eslint/js' imported from /tmp/BgUtils/eslint.config.js
npm error     at Object.getPackageJSONURL (node:internal/modules/package_json_reader:267:9)
npm error     at packageResolve (node:internal/modules/esm/resolve:768:81)
npm error     at moduleResolve (node:internal/modules/esm/resolve:854:18)
npm error     at defaultResolve (node:internal/modules/esm/resolve:984:11)
npm error     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:688:12)
npm error     at #cachedDefaultResolve (node:internal/modules/esm/loader:612:25)
npm error     at ModuleLoader.resolve (node:internal/modules/esm/loader:595:38)
npm error     at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:248:38)
npm error     at ModuleJob._link (node:internal/modules/esm/module_job:136:49)
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-28T16_15_19_341Z-debug-0.log
```
And this, combining the two (running `npm install`˙in `examples/node`, then going back to root to do `npm run build`):
```
git clone https://github.com/LuanRT/BgUtils
cd BgUtils/examples/node/
npm install
cd ../..
npm run build
```
Result:
```
> bgutils-js@3.1.0 build
> npm run clean && npm run lint && npm run build:esm && npm run bundle:node


> bgutils-js@3.1.0 clean
> npx rimraf ./dist ./bundle


> bgutils-js@3.1.0 lint
> npx eslint ./src/**/*.ts


Oops! Something went wrong! :(

ESLint: 9.17.0

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@eslint/js' imported from /tmp/BgUtils/eslint.config.js
    at Object.getPackageJSONURL (node:internal/modules/package_json_reader:267:9)
    at packageResolve (node:internal/modules/esm/resolve:768:81)
    at moduleResolve (node:internal/modules/esm/resolve:854:18)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:688:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:612:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:595:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:248:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:136:49)
```
I am totally lost now...

**Comment by LuanRT** [comment]
I'm sorry if I sound confusing, it's just how TypeScript packages work if you're building from source.
This is what you're supposed to see after the dependencies are installed:
![Screenshot 2024-12-28 143231](https://github.com/user-attachments/assets/c81a9ba4-bf41-4122-842b-5256a0fe277d)

I don't know why the `@eslint/js` dev dep isn't installing for you. Maybe just try installing the library from NPM as I said earlier so that you don't have to compile it yourself.

**Comment by TCH68k** [comment]
Okay, i got figured out what was the problem...

Since the `nodejs` package shipped by Debian 11 is very old (v12), i had installed a portable v23 node.js into `/opt/` as a standalone package, downloaded from nodejs.org and made some wrapper scripts with `$NODE_PATH` set to `/opt/node.js/$VER/lib/node_modules` and `/opt/node.js/$VER/bin` added to `$PATH`.
However, `npm` has always installed `node_modules` into the CWD, instead of `/opt/node.js/$VER/lib/node_modules` and the installed packages never worked in the next directory i've been working in. After some searching, i've found, that `-g` has to be specified to work in global mode. I've put that flag into the wrapper script. And that was the reason behind `npm install` failing... Sorry for that. NPM is extremely illogical for me and therefore is as much confusing.

So, i've removed the `-g` flag from the wrapper script and retried.
```
git clone https://github.com/LuanRT/BgUtils
cd BgUtils/
npm install
npm run build
cd examples/node
npm install
npx tsx .
```
And it worked. Thank you for the help.
Just one last question: could it be made that global mode would work? I'd like to install `jsdom`, `tsx`, `eslint` and `rimraf` into the global `node_modules`, because this way is very redundant... (Not with just BgUtils, but the entire NPM packaging.)

**Comment by LuanRT** [comment]
You won't need any of those dev dependencies if you install the library from NPM. Then from there, you can install `jsdom` & other required dependencies wherever you want.
