### ISSUE TITLE
How to specify format?

### ISSUE THREAD

**Issue by TCH68k** [LuanRT/BgUtils#14]
### Question

By tweaking [https://github.com/LuanRT/BgUtils/blob/main/examples/node/index.ts](https://github.com/LuanRT/BgUtils/blob/main/examples/node/index.ts#L64), i can set the watch code, the stream type and it works for both audio and video perfectly. This tool is just what i needed all along.

However, something is not clear for me. If i set the `quality` prop here, then it dies with this message:
```
(node:30740) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Session Info: {
  visitorData: 'CgtuYTh6YlpiMldwZyic9sG7BjIiCgJIVRIcEhgSFhMLFBUWFwwYGRobHB0eHw4PIBAREiEgaQ%3D%3D',
  placeholderPoToken: 'Ilgtly2WSudWrG7wWeJ0w0WhdPtd_mD7SeB37kT0FORqoG_9ZP5u8Gfee8Vk9Gj_SsRr_2Dba9V4wGvgWs5qxUL1ZdUd8mXgGcdk1WzFaP5o8EzGCKRpsh7T',
  poToken: 'MpgB7153dJU-yvrvYm8y6hKllpV7bjrZmF8-aV3CJUu_zAGP---OuN2To-IHGbdLH5HnZI29slw6q-fmDQI0dxPWDZuensVcCGO2MsFBrVJdImR9XZ8hslDzi9dDYiM5MqVSfVjW5KQwYON1HnO29_ubWQ1actoF4O0i_gK8xQUmDHWMwfPxPOYivrX-s7sAyAgGQfexIbpIFhY=',
  integrityTokenData: {
    integrityToken: 'GEZ/LG9seiUZTkymlcSGA7VR3oEG+2ClmPot41lZDVluw94hWx2L08rGyQRhHQlTdUDiLRz3dMDpsck2',
    estimatedTtlSecs: 43200,
    mintRefreshThreshold: 100,
    websafeFallbackToken: undefined
  }
}
file:///tmp/BgUtils/examples/node/node_modules/youtubei.js/dist/src/utils/FormatUtils.js:130
        throw new InnertubeError('No matching formats found', { options });
              ^

InnertubeError: No matching formats found
    at Module.chooseFormat (file:///tmp/BgUtils/examples/node/node_modules/youtubei.js/dist/src/utils/FormatUtils.js:130:15)
    at VideoInfo.chooseFormat (file:///tmp/BgUtils/examples/node/node_modules/youtubei.js/dist/src/core/mixins/MediaInfo.js:92:28)
    at <anonymous> (/tmp/BgUtils/examples/node/index.ts:65:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  info: { options: { quality: '136', type: 'video' } },
  date: 2024-12-28T22:27:08.022Z,
  version: '12.2.0'
}

Node.js v23.5.0
```
Which is strange, as i know that this format does exist. I am sure i am doing it wrong, but i am not sure what, because `best` worked.

Or perhaps i am mistaken and the format of 136 only exists for the Android streams, while the tool tried to fetch the iOS or web ones?

### Checklist

- [x] I am running the latest version.
- [x] I checked the documentation and found no answer.
- [x] I have searched the existing issues and made sure this is not a duplicate.
- [x] I have provided sufficient information.

**Comment by LuanRT** [comment]
Instead of relying on `chooseFormat`, try:
```ts
if (info.streaming_data) {
  const format = info.streaming_data?.adaptive_formats.find((fmt) => fmt.itag === 136);

  if (format) {
    console.log('Stream URL:', format.decipher(innertube.session.player));
  }
}
```

Also, this is unrelated to this project. In the future, please refer to ytjs' documentation or ask for help in the Discord server.

PS: Don't change the InnerTube client being used, bgutils can only generate WebPO tokens.

**Comment by TCH68k** [comment]
Okay, thanks for the help.
